version: 2.1
jobs:
  compile:
   docker:
      - image: wizardprjkt/build:kernel
   steps:
      - run:
          command: |
            git clone --depth=1 https://github.com/znieb/kernel_asus_sdm660-b hmp kernel && cd kernel
            curl https://raw.githubusercontent.com/znieb/cooking-kernel/circle/build.sh > run.sh
            source run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
